class AppLocalizations {
  static final Map<String, Map<String, String>> _translations = {
    'ar': _ar,
    'en': _en,
  };

  static const Map<String, String> _ar = {
    // Common
    'common.app_name': 'المختبر',
    'common.loading': 'جار التحميل...',
    'common.error': 'حدث خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.done': 'تم',
    'common.submit': 'إرسال',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.no_data': 'لا توجد بيانات',
    'common.no_results': 'لا توجد نتائج',
    'common.no_internet': 'لا يوجد اتصال بالإنترنت',
    'common.something_wrong': 'حدث خطأ ما، حاول مرة أخرى',
    'common.try_again': 'حاول مرة أخرى',
    'common.view_all': 'عرض الكل',
    'common.see_more': 'عرض المزيد',
    'common.see_less': 'عرض أقل',
    'common.select': 'اختيار',
    'common.selected': 'مختار',
    'common.optional': 'اختياري',
    'common.required': 'إلزامي',
    'common.continue_text': 'استمرار',
    'common.skip': 'تخطي',
    'common.success': 'تم بنجاح',
    'common.failure': 'فشل',
    'common.warning': 'تحذير',
    'common.info': 'معلومة',
    'common.confirm_action': 'تأكيد العملية',
    'common.are_you_sure': 'هل أنت متأكد؟',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'حسناً',
    'common.today': 'اليوم',
    'common.yesterday': 'أمس',
    'common.tomorrow': 'غداً',
    'common.days_ago': 'منذ {days} أيام',
    'common.hours_ago': 'منذ {hours} ساعات',
    'common.minutes_ago': 'منذ {minutes} دقائق',
    'common.just_now': 'الآن',
    'common.all': 'الكل',
    'common.male': 'ذكر',
    'common.female': 'أنثى',

    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirm_password': 'تأكيد كلمة المرور',
    'auth.phone': 'رقم الهاتف',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.reset_password': 'إعادة تعيين كلمة المرور',
    'auth.new_password': 'كلمة المرور الجديدة',
    'auth.otp': 'رمز التحقق',
    'auth.otp_sent': 'تم إرسال رمز التحقق إلى {contact}',
    'auth.verify_otp': 'تأكيد رمز التحقق',
    'auth.resend_otp': 'إعادة إرسال الرمز',
    'auth.otp_expired': 'انتهت صلاحية الرمز',
    'auth.login_success': 'تم تسجيل الدخول بنجاح',
    'auth.register_success': 'تم إنشاء الحساب بنجاح',
    'auth.logout_success': 'تم تسجيل الخروج بنجاح',
    'auth.invalid_credentials': 'بيانات الدخول غير صحيحة',
    'auth.email_required': 'البريد الإلكتروني مطلوب',
    'auth.invalid_email': 'البريد الإلكتروني غير صالح',
    'auth.password_required': 'كلمة المرور مطلوبة',
    'auth.password_length': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'auth.password_mismatch': 'كلمة المرور غير متطابقة',
    'auth.phone_required': 'رقم الهاتف مطلوب',
    'auth.invalid_phone': 'رقم الهاتف غير صالح',
    'auth.name_required': 'الاسم مطلوب',
    'auth.name_ar': 'الاسم (بالعربية)',
    'auth.name_en': 'الاسم (بالإنجليزية)',
    'auth.biometric_login': 'بصمة الوجه / الإصبع',
    'auth.use_biometric': 'استخدام بصمة الوجه أو الإصبع لتسجيل الدخول',
    'auth.setup_biometric': 'إعداد البصمة',
    'auth.skip_biometric': 'تخطي الآن',
    'auth.enable_2fa': 'تفعيل التحقق بخطوتين',
    'auth.disable_2fa': 'إلغاء التحقق بخطوتين',
    'auth.verify_2fa': 'تأكيد التحقق بخطوتين',
    'auth.google_login': 'تسجيل الدخول بواسطة Google',
    'auth.apple_login': 'تسجيل الدخول بواسطة Apple',
    'auth.welcome_back': 'مرحباً بعودتك!',
    'auth.create_account': 'إنشاء حساب جديد',
    'auth.password_strength': 'قوة كلمة المرور',
    'auth.weak': 'ضعيفة',
    'auth.medium': 'متوسطة',
    'auth.strong': 'قوية',

    // Navigation
    'nav.home': 'الرئيسية',
    'nav.appointments': 'المواعيد',
    'nav.results': 'النتائج',
    'nav.more': 'المزيد',
    'nav.branches': 'الفروع',
    'nav.payments': 'المدفوعات',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'nav.notifications': 'الإشعارات',
    'nav.family': 'أفراد العائلة',
    'nav.medicine': 'تذكير الأدوية',
    'nav.ai_assistant': 'المساعد الذكي',
    'nav.about': 'حول التطبيق',
    'nav.contact_us': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',

    // Appointments
    'appointments.title': 'المواعيد',
    'appointments.book': 'حجز موعد',
    'appointments.upcoming': 'القادمة',
    'appointments.past': 'السابقة',
    'appointments.cancelled': 'ملغية',
    'appointments.select_branch': 'اختر الفرع',
    'appointments.select_tests': 'اختر الفحوصات',
    'appointments.select_date': 'اختر التاريخ',
    'appointments.select_time': 'اختر الوقت',
    'appointments.select_patient': 'اختر المريض',
    'appointments.confirm_booking': 'تأكيد الحجز',
    'appointments.payment': 'الدفع',
    'appointments.insurance': 'التأمين الصحي',
    'appointments.home_visit': 'زيارة منزلية',
    'appointments.patient_self': 'نفسي',
    'appointments.patient_family': 'أحد أفراد العائلة',
    'appointments.slots_unavailable': 'لا توجد مواعيد متاحة في هذا التاريخ',
    'appointments.booking_success': 'تم حجز الموعد بنجاح',
    'appointments.booking_failed': 'فشل حجز الموعد',
    'appointments.cancel_confirm': 'هل أنت متأكد من إلغاء الموعد؟',
    'appointments.cancel_success': 'تم إلغاء الموعد بنجاح',
    'appointments.reschedule': 'إعادة جدولة',
    'appointments.queue_status': 'حالة الدور',
    'appointments.queue_number': 'رقم الدور',
    'appointments.your_position': 'موقعك في الانتظار',
    'appointments.estimated_wait': 'وقت الانتظار المتوقع',
    'appointments.you_are_called': 'تم مناداتك!',
    'appointments.please_proceed': 'يرجى التوجه إلى القسم المحدد',

    // Results
    'results.title': 'نتائج الفحوصات',
    'results.detail': 'تفاصيل النتيجة',
    'results.pdf': 'عرض PDF',
    'results.share': 'مشاركة',
    'results.compare': 'مقارنة',
    'results.timeline': 'الخط الزمني',
    'results.ai_explain': 'شرح الذكاء الاصطناعي',
    'results.all': 'جميع الفحوصات',
    'results.abnormal': 'غير طبيعي',
    'results.critical': 'حرج',
    'results.normal': 'طبيعي',
    'results.pending': 'قيد الانتظار',
    'results.completed': 'مكتمل',
    'results.no_results': 'لا توجد نتائج',
    'results.search_hint': 'ابحث عن فحص...',
    'results.test_name': 'اسم الفحص',
    'results.result_value': 'النتيجة',
    'results.reference_range': 'النطاق المرجعي',
    'results.unit': 'الوحدة',
    'results.status': 'الحالة',
    'results.comparison': 'مقارنة النتائج',
    'results.period': 'الفترة',
    'results.export_csv': 'تصدير CSV',
    'results.download_report': 'تحميل التقرير',
    'results.verify_qr': 'التحقق بواسطة QR',

    // Payments
    'payments.title': 'المدفوعات',
    'payments.wallet': 'المحفظة',
    'payments.balance': 'الرصيد',
    'payments.add_balance': 'إضافة رصيد',
    'payments.invoices': 'الفواتير',
    'payments.invoice_detail': 'تفاصيل الفاتورة',
    'payments.pay': 'دفع',
    'payments.pay_now': 'ادفع الآن',
    'payments.payment_method': 'طريقة الدفع',
    'payments.card': 'بطاقة ائتمان',
    'payments.apple_pay': 'Apple Pay',
    'payments.google_pay': 'Google Pay',
    'payments.stc_pay': 'STC Pay',
    'payments.wallet_pay': 'المحفظة',
    'payments.transactions': 'المعاملات',
    'payments.installments': 'التقسيط',
    'payments.subscriptions': 'الاشتراكات',
    'payments.payment_success': 'تم الدفع بنجاح',
    'payments.payment_failed': 'فشلت عملية الدفع',
    'payments.receipt': 'الإيصال',
    'payments.amount': 'المبلغ',
    'payments.due_date': 'تاريخ الاستحقاق',
    'payments.paid': 'مدفوع',
    'payments.unpaid': 'غير مدفوع',
    'payments.overdue': 'متأخر',

    // Branches
    'branches.title': 'الفروع',
    'branches.nearby': 'الفروع القريبة',
    'branches.detail': 'تفاصيل الفرع',
    'branches.directions': 'الاتجاهات',
    'branches.call': 'اتصال',
    'branches.book_appointment': 'حجز موعد',
    'branches.working_hours': 'ساعات العمل',
    'branches.open': 'مفتوح',
    'branches.closed': 'مغلق',
    'branches.services': 'الخدمات',
    'branches.reviews': 'التقييمات',
    'branches.distance': 'المسافة',
    'branches.search_hint': 'ابحث عن فرع...',

    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.personal_info': 'المعلومات الشخصية',
    'profile.insurance': 'معلومات التأمين',
    'profile.emergency_contact': 'جهة الاتصال في الطوارئ',
    'profile.change_password': 'تغيير كلمة المرور',
    'profile.language': 'اللغة',
    'profile.theme': 'السمة',
    'profile.biometric': 'بصمة الوجه / الإصبع',
    'profile.notification_settings': 'إعدادات الإشعارات',

    // Family
    'family.title': 'أفراد العائلة',
    'family.add': 'إضافة فرد',
    'family.edit': 'تعديل بيانات الفرد',
    'family.delete': 'حذف الفرد',
    'family.relationship': 'صلة القرابة',
    'family.spouse': 'زوج/زوجة',
    'family.child': 'ابن/ابنة',
    'family.parent': 'والد/والدة',
    'family.sibling': 'أخ/أخت',
    'family.other': 'آخر',
    'family.dob': 'تاريخ الميلاد',
    'family.gender': 'الجنس',
    'family.blood_type': 'فصيلة الدم',
    'family.insurance': 'معلومات التأمين',
    'family.dependent': 'تابع',
    'family.no_members': 'لا يوجد أفراد عائلة',
    'family.add_hint': 'أضف أفراد عائلتك لإدارة مواعيدهم ونتائجهم',

    // Medicine
    'medicine.title': 'تذكير الأدوية',
    'medicine.add': 'إضافة دواء',
    'medicine.edit': 'تعديل الدواء',
    'medicine.delete': 'حذف الدواء',
    'medicine.name': 'اسم الدواء',
    'medicine.dosage': 'الجرعة',
    'medicine.frequency': 'التكرار',
    'medicine.daily': 'يومي',
    'medicine.weekly': 'أسبوعي',
    'medicine.monthly': 'شهري',
    'medicine.time': 'الوقت',
    'medicine.notes': 'ملاحظات',
    'medicine.date_range': 'الفترة',
    'medicine.start_date': 'تاريخ البداية',
    'medicine.end_date': 'تاريخ النهاية',
    'medicine.refill_reminder': 'تذكير إعادة الصرف',
    'medicine.no_medicines': 'لا توجد أدوية',
    'medicine.adherence': 'الالتزام',
    'medicine.taken': 'تم تناوله',
    'medicine.missed': 'فاتني',
    'medicine.upcoming': 'القادم',

    // AI Assistant
    'ai.title': 'المساعد الذكي',
    'ai.placeholder': 'اسأل عن فحوصاتك، تفسير نتائج، أو معلومات صحية...',
    'ai.typing': 'المساعد يكتب...',
    'ai.suggestions': 'اقتراحات',
    'ai.suggestion1': 'ماذا تعني نتيجة فحص السكر؟',
    'ai.suggestion2': ' explain my latest blood test',
    'ai.suggestion3': 'What should I eat before a fasting test?',
    'ai.voice_search': 'بحث صوتي',
    'ai.listening': 'جار الاستماع...',
    'ai.not_heard': 'لم نتمكن من سماعك، حاول مرة أخرى',
    'ai.clear_chat': 'مسح المحادثة',
    'ai.error_message': 'عذراً، حدث خطأ. حاول مرة أخرى',

    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.mark_all_read': 'تحديد الكل كمقروء',
    'notifications.result_ready': 'نتيجة الفحص جاهزة',
    'notifications.appointment_reminder': 'تذكير موعد',
    'notifications.payment_due': 'استحقاق دفع',
    'notifications.promotion': 'عرض خاص',
    'notifications.general': 'إشعار عام',

    // Settings
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.theme': 'السمة',
    'settings.light': 'فاتح',
    'settings.dark': 'داكن',
    'settings.system': 'النظام',
    'settings.biometric': 'بصمة الوجه / الإصبع',
    'settings.notifications': 'الإشعارات',
    'settings.push_notifications': 'إشعارات الدفع',
    'settings.email_notifications': 'إشعارات البريد الإلكتروني',
    'settings.sms_notifications': 'إشعارات الرسائل النصية',
    'settings.cache': 'مسح الذاكرة المؤقتة',
    'settings.cache_cleared': 'تم مسح الذاكرة المؤقتة',
    'settings.version': 'الإصدار',
    'settings.about': 'حول التطبيق',
    'settings.logout': 'تسجيل الخروج',
    'settings.logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',

    // Errors
    'errors.network': 'خطأ في الشبكة، تحقق من اتصالك بالإنترنت',
    'errors.server': 'خطأ في الخادم، حاول مرة أخرى لاحقاً',
    'errors.timeout': 'انتهت مهلة الطلب، حاول مرة أخرى',
    'errors.unauthorized': 'غير مصرح، يرجى تسجيل الدخول مرة أخرى',
    'errors.forbidden': 'ليس لديك صلاحية للوصول',
    'errors.not_found': 'العنصر غير موجود',
    'errors.validation': 'خطأ في البيانات المدخلة',
    'errors.unknown': 'خطأ غير متوقع',
    'errors.session_expired': 'انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى',
  };

  static const Map<String, String> _en = {
    // Common
    'common.app_name': 'Al Mokhtabar',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.no_data': 'No data available',
    'common.no_results': 'No results found',
    'common.no_internet': 'No internet connection',
    'common.something_wrong': 'Something went wrong, please try again',
    'common.try_again': 'Try again',
    'common.view_all': 'View all',
    'common.see_more': 'See more',
    'common.see_less': 'See less',
    'common.select': 'Select',
    'common.selected': 'Selected',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.continue_text': 'Continue',
    'common.skip': 'Skip',
    'common.success': 'Success',
    'common.failure': 'Failed',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.confirm_action': 'Confirm action',
    'common.are_you_sure': 'Are you sure?',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.days_ago': '{days} days ago',
    'common.hours_ago': '{hours} hours ago',
    'common.minutes_ago': '{minutes} minutes ago',
    'common.just_now': 'Just now',
    'common.all': 'All',
    'common.male': 'Male',
    'common.female': 'Female',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Create Account',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.phone': 'Phone Number',
    'auth.forgot_password': 'Forgot Password?',
    'auth.reset_password': 'Reset Password',
    'auth.new_password': 'New Password',
    'auth.otp': 'Verification Code',
    'auth.otp_sent': 'Verification code sent to {contact}',
    'auth.verify_otp': 'Verify Code',
    'auth.resend_otp': 'Resend Code',
    'auth.otp_expired': 'Code expired',
    'auth.login_success': 'Logged in successfully',
    'auth.register_success': 'Account created successfully',
    'auth.logout_success': 'Logged out successfully',
    'auth.invalid_credentials': 'Invalid credentials',
    'auth.email_required': 'Email is required',
    'auth.invalid_email': 'Invalid email address',
    'auth.password_required': 'Password is required',
    'auth.password_length': 'Password must be at least 8 characters',
    'auth.password_mismatch': 'Passwords do not match',
    'auth.phone_required': 'Phone number is required',
    'auth.invalid_phone': 'Invalid phone number',
    'auth.name_required': 'Name is required',
    'auth.name_ar': 'Name (Arabic)',
    'auth.name_en': 'Name (English)',
    'auth.biometric_login': 'Face ID / Fingerprint',
    'auth.use_biometric': 'Use Face ID or Fingerprint to login',
    'auth.setup_biometric': 'Set up Biometrics',
    'auth.skip_biometric': 'Skip for now',
    'auth.enable_2fa': 'Enable Two-Factor Auth',
    'auth.disable_2fa': 'Disable Two-Factor Auth',
    'auth.verify_2fa': 'Verify Two-Factor Auth',
    'auth.google_login': 'Sign in with Google',
    'auth.apple_login': 'Sign in with Apple',
    'auth.welcome_back': 'Welcome Back!',
    'auth.create_account': 'Create New Account',
    'auth.password_strength': 'Password Strength',
    'auth.weak': 'Weak',
    'auth.medium': 'Medium',
    'auth.strong': 'Strong',

    // Navigation
    'nav.home': 'Home',
    'nav.appointments': 'Appointments',
    'nav.results': 'Results',
    'nav.more': 'More',
    'nav.branches': 'Branches',
    'nav.payments': 'Payments',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.notifications': 'Notifications',
    'nav.family': 'Family',
    'nav.medicine': 'Medicine',
    'nav.ai_assistant': 'AI Assistant',
    'nav.about': 'About',
    'nav.contact_us': 'Contact Us',
    'nav.faq': 'FAQ',

    // Appointments
    'appointments.title': 'Appointments',
    'appointments.book': 'Book Appointment',
    'appointments.upcoming': 'Upcoming',
    'appointments.past': 'Past',
    'appointments.cancelled': 'Cancelled',
    'appointments.select_branch': 'Select Branch',
    'appointments.select_tests': 'Select Tests',
    'appointments.select_date': 'Select Date',
    'appointments.select_time': 'Select Time',
    'appointments.select_patient': 'Select Patient',
    'appointments.confirm_booking': 'Confirm Booking',
    'appointments.payment': 'Payment',
    'appointments.insurance': 'Insurance',
    'appointments.home_visit': 'Home Visit',
    'appointments.patient_self': 'Myself',
    'appointments.patient_family': 'Family Member',
    'appointments.slots_unavailable': 'No slots available on this date',
    'appointments.booking_success': 'Appointment booked successfully',
    'appointments.booking_failed': 'Failed to book appointment',
    'appointments.cancel_confirm': 'Are you sure you want to cancel?',
    'appointments.cancel_success': 'Appointment cancelled successfully',
    'appointments.reschedule': 'Reschedule',
    'appointments.queue_status': 'Queue Status',
    'appointments.queue_number': 'Queue Number',
    'appointments.your_position': 'Your Position',
    'appointments.estimated_wait': 'Estimated Wait',
    'appointments.you_are_called': 'You are being called!',
    'appointments.please_proceed': 'Please proceed to the designated area',

    // Results
    'results.title': 'Test Results',
    'results.detail': 'Result Details',
    'results.pdf': 'View PDF',
    'results.share': 'Share',
    'results.compare': 'Compare',
    'results.timeline': 'Timeline',
    'results.ai_explain': 'AI Explanation',
    'results.all': 'All Tests',
    'results.abnormal': 'Abnormal',
    'results.critical': 'Critical',
    'results.normal': 'Normal',
    'results.pending': 'Pending',
    'results.completed': 'Completed',
    'results.no_results': 'No results found',
    'results.search_hint': 'Search tests...',
    'results.test_name': 'Test Name',
    'results.result_value': 'Result',
    'results.reference_range': 'Reference Range',
    'results.unit': 'Unit',
    'results.status': 'Status',
    'results.comparison': 'Result Comparison',
    'results.period': 'Period',
    'results.export_csv': 'Export CSV',
    'results.download_report': 'Download Report',
    'results.verify_qr': 'Verify with QR',

    // Payments
    'payments.title': 'Payments',
    'payments.wallet': 'Wallet',
    'payments.balance': 'Balance',
    'payments.add_balance': 'Add Balance',
    'payments.invoices': 'Invoices',
    'payments.invoice_detail': 'Invoice Details',
    'payments.pay': 'Pay',
    'payments.pay_now': 'Pay Now',
    'payments.payment_method': 'Payment Method',
    'payments.card': 'Credit Card',
    'payments.apple_pay': 'Apple Pay',
    'payments.google_pay': 'Google Pay',
    'payments.stc_pay': 'STC Pay',
    'payments.wallet_pay': 'Wallet',
    'payments.transactions': 'Transactions',
    'payments.installments': 'Installments',
    'payments.subscriptions': 'Subscriptions',
    'payments.payment_success': 'Payment successful',
    'payments.payment_failed': 'Payment failed',
    'payments.receipt': 'Receipt',
    'payments.amount': 'Amount',
    'payments.due_date': 'Due Date',
    'payments.paid': 'Paid',
    'payments.unpaid': 'Unpaid',
    'payments.overdue': 'Overdue',

    // Branches
    'branches.title': 'Branches',
    'branches.nearby': 'Nearby Branches',
    'branches.detail': 'Branch Details',
    'branches.directions': 'Directions',
    'branches.call': 'Call',
    'branches.book_appointment': 'Book Appointment',
    'branches.working_hours': 'Working Hours',
    'branches.open': 'Open',
    'branches.closed': 'Closed',
    'branches.services': 'Services',
    'branches.reviews': 'Reviews',
    'branches.distance': 'Distance',
    'branches.search_hint': 'Search branches...',

    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.personal_info': 'Personal Information',
    'profile.insurance': 'Insurance Info',
    'profile.emergency_contact': 'Emergency Contact',
    'profile.change_password': 'Change Password',
    'profile.language': 'Language',
    'profile.theme': 'Theme',
    'profile.biometric': 'Face ID / Fingerprint',
    'profile.notification_settings': 'Notification Settings',

    // Family
    'family.title': 'Family Members',
    'family.add': 'Add Member',
    'family.edit': 'Edit Member',
    'family.delete': 'Delete Member',
    'family.relationship': 'Relationship',
    'family.spouse': 'Spouse',
    'family.child': 'Child',
    'family.parent': 'Parent',
    'family.sibling': 'Sibling',
    'family.other': 'Other',
    'family.dob': 'Date of Birth',
    'family.gender': 'Gender',
    'family.blood_type': 'Blood Type',
    'family.insurance': 'Insurance Info',
    'family.dependent': 'Dependent',
    'family.no_members': 'No family members',
    'family.add_hint': 'Add family members to manage their appointments and results',

    // Medicine
    'medicine.title': 'Medicine Reminders',
    'medicine.add': 'Add Medicine',
    'medicine.edit': 'Edit Medicine',
    'medicine.delete': 'Delete Medicine',
    'medicine.name': 'Medicine Name',
    'medicine.dosage': 'Dosage',
    'medicine.frequency': 'Frequency',
    'medicine.daily': 'Daily',
    'medicine.weekly': 'Weekly',
    'medicine.monthly': 'Monthly',
    'medicine.time': 'Time',
    'medicine.notes': 'Notes',
    'medicine.date_range': 'Date Range',
    'medicine.start_date': 'Start Date',
    'medicine.end_date': 'End Date',
    'medicine.refill_reminder': 'Refill Reminder',
    'medicine.no_medicines': 'No medicines',
    'medicine.adherence': 'Adherence',
    'medicine.taken': 'Taken',
    'medicine.missed': 'Missed',
    'medicine.upcoming': 'Upcoming',

    // AI Assistant
    'ai.title': 'AI Assistant',
    'ai.placeholder': 'Ask about your tests, interpret results, or health information...',
    'ai.typing': 'Assistant is typing...',
    'ai.suggestions': 'Suggestions',
    'ai.suggestion1': 'What does my blood sugar result mean?',
    'ai.suggestion2': 'Explain my latest blood test',
    'ai.suggestion3': 'What should I eat before a fasting test?',
    'ai.voice_search': 'Voice Search',
    'ai.listening': 'Listening...',
    'ai.not_heard': "We couldn't hear you, please try again",
    'ai.clear_chat': 'Clear Chat',
    'ai.error_message': 'Sorry, an error occurred. Please try again',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.mark_all_read': 'Mark All Read',
    'notifications.result_ready': 'Test Result Ready',
    'notifications.appointment_reminder': 'Appointment Reminder',
    'notifications.payment_due': 'Payment Due',
    'notifications.promotion': 'Promotion',
    'notifications.general': 'General',

    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.biometric': 'Face ID / Fingerprint',
    'settings.notifications': 'Notifications',
    'settings.push_notifications': 'Push Notifications',
    'settings.email_notifications': 'Email Notifications',
    'settings.sms_notifications': 'SMS Notifications',
    'settings.cache': 'Clear Cache',
    'settings.cache_cleared': 'Cache cleared',
    'settings.version': 'Version',
    'settings.about': 'About',
    'settings.logout': 'Logout',
    'settings.logout_confirm': 'Are you sure you want to logout?',

    // Errors
    'errors.network': 'Network error, check your connection',
    'errors.server': 'Server error, please try again later',
    'errors.timeout': 'Request timed out, please try again',
    'errors.unauthorized': 'Unauthorized, please login again',
    'errors.forbidden': 'You do not have permission',
    'errors.not_found': 'Resource not found',
    'errors.validation': 'Validation error',
    'errors.unknown': 'Unexpected error',
    'errors.session_expired': 'Session expired, please login again',
  };

  static String _locale = 'ar';

  static String get locale => _locale;

  static void setLocale(String localeCode) {
    _locale = localeCode;
  }

  static String t(String key, {Map<String, String>? args}) {
    final langMap = _translations[_locale] ?? _ar;
    String text = langMap[key] ?? _ar[key] ?? key;
    if (args != null) {
      for (final entry in args.entries) {
        text = text.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return text;
  }

  static String plural(String key, int count, {Map<String, String>? args}) {
    final pluralKey = '$key.$count';
    String? result;
    if (count == 1) {
      result = _tryGet('$key.singular', args);
    }
    result ??= _tryGet(pluralKey, args);
    result ??= _tryGet('$key.plural', args);
    result ??= t(key, args: {
      if (args != null) ...args,
      'count': count.toString(),
    });
    return result;
  }

  static String? _tryGet(String key, Map<String, String>? args) {
    final langMap = _translations[_locale] ?? _ar;
    final text = langMap[key];
    if (text == null) return null;
    if (args == null) return text;
    String result = text;
    for (final entry in args.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }

  static bool get isRtl => _locale == 'ar';
}
