{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "almokhtabar.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | default "almokhtabar" }}
  labels:
    {{- include "almokhtabar.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
